name: HUJRA Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout HUJRA
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Create web folder
        run: |
          mkdir -p www
          cp index.html www/
          cp style.css www/
          cp script.js www/
          cp google-auth-config.js www/


      - name: Install dependencies
        run: npm install


      - name: Add Android platform
        run: npx cap add android


      - name: Sync Capacitor
        run: npx cap sync android


      - name: Make Gradle executable
        run: chmod +x android/gradlew


      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug


      - name: Upload HUJRA APK
        uses: actions/upload-artifact@v4
        with:
          name: HUJRA-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
